### PR TITLE
errors

### PR DESCRIPTION
**Pull request by bethanyhaubert**

### CODE REVIEW

**Comment by bethanyhaubert** [comment]
We stored an array inside session["temporary_error_message"]. Now we're trying to loop it like a normal array. It will loop through it, but then ultimately return the original array, which is what it's displaying in our view. Tried a couple things in pry. See below:

```
[2] pry(#<MyApp>)> @error_object.each { |error_message| puts error_message }
Name cannot be blank
An account already exists for this email address.
=> ["Name cannot be blank", "An account already exists for this email address."]
```

```
[1] pry(#<MyApp>)> @error_object.each do |x|
[1] pry(#<MyApp>)*   puts x
[1] pry(#<MyApp>)* end
Name cannot be blank
An account already exists for this email address.
=> ["Name cannot be blank", "An account already exists for this email address."]
```

**Comment by bethanyhaubert** [comment]
But not the one in the comment above. still need help with that

**Comment by halfghaninne** [comment]
`puts` was something that we used to display a string in the command line interface.

Try setting up [your loop](https://github.com/bethanyhaubert/02-29-pair-project/blob/b60a60b6cce0a86733002fd8d14dc2e34c7dc02c/app/views/layout.erb#L68) like:

```
<% @error_object.each do |error_message| %>
    <%= error_message %>
<% end %>
```

**Comment by bethanyhaubert** [comment]
```
<% @error_object.each do |error_message| %>
    <%= error_message %>
<% end %>
```

that was our original code. it wasn't working either

**Comment by halfghaninne** [comment]
Can I come up and take a look?

**Pull request merged**
